name: My_first_workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: List and Read file
              run: |
                echo "Hello github action"
                ls -ltra
                cat README.md
            